local_backend: true
backend:
  name: github
  repo: 903158800-dev/aurora-filtech.com # 您的 GitHub 仓库名
  branch: main # 或者 master，取决于您的默认分支
  
media_folder: "design_premium_gray/assets" # 图片上传的目录
public_folder: "assets" # 网站引用图片的相对路径

collections:
  - name: "products" # 后台显示的集合名称
    label: "Products (产品管理)"
    folder: "design_light/content/products"
    create: true
    slug: "{{slug}}" # 文件名生成规则
    fields:
      - {label: "Product Name (产品名称)", name: "title", widget: "string"}
      - {label: "SEO Description (SEO 描述)", name: "description", widget: "text"}
      - {label: "Featured Image (主图)", name: "image", widget: "image", required: false}
      - {label: "Content (详细内容)", name: "body", widget: "markdown"}