// site-seo 行业页 + 应用页 + 博客 + 术语表数据
// 内容依据《SEO-调研报告.md》《SEO-词库补充.md》

// ---- 行业页(6) ----
const industries = {
  "wood-based-panels": {
    url: `/industries/wood-based-panels/`, name: "Wood-based Panels",
    title: "Wood-based Panel Belts | MDF, OSB & Particleboard | Aurora Filtech",
    desc: "Forming fabrics, dryer fabrics, spiral dryer belts and square mesh belts for MDF, OSB and particleboard lines. Dieffenbacher / Siempelkamp type plants.",
    kicker: "Industries · Wood-based Panels",
    intro: `From the forming line to the press outfeed, every deck of an MDF, OSB or particleboard line runs on woven and spiral fabrics. Aurora supplies the belts that matter at each stage — forming and pre-press, the drying decks, the biomass dryers — cut to the common plant platforms.`,
    banner: { img: "/qfy-content/uploads/df/wood-banner.jpg", alt: "Dieffenbacher-type wood panel production line running board forming", w: 1000, h: 500,
      cap: "Wood panel forming line (Dieffenbacher-type) — the environment Aurora panel fabrics are built for." },
    processes: [
      { t: "Mat forming & pre-press", tag: "Anti-static fabrics", link: "dryer-fabric",
        img: "/qfy-content/uploads/df/hero.jpg", alt: "Anti-static dryer fabric close-up with conductive monofilaments for wood panel forming lines", w: 1200, h: 525,
        cap: "Anti-static monofilament construction — the flagship panel-line fabric.",
        txt: "On MDF, OSB and particleboard forming lines, resin dust and high-speed friction charge the belt until fibers cling and mark the board. Anti-static monofilament drains the charge in the yarn itself; the spiral-linked enhanced seam survives the pre-press nip." },
      { t: "Pre-press belt, filmed on an MDF line", link: "dryer-fabric",
        vid: "/qfy-content/uploads/df/prepress.mp4", poster: "/qfy-content/uploads/df/as-mono.jpg",
        cap: "Anti-static pre-press belt in live operation.",
        txt: "Our anti-static belt working the pre-press section of a Chinese MDF plant (Dieffenbacher-type line) — clean release and no dust cling, filmed as supplied." },
      { t: "Release-critical duties — 4106S silicone-coated", tag: "Panel lines only", link: "dryer-fabric",
        img: "/qfy-content/uploads/df/4106s.jpg", alt: "Type 4106S dryer belt with high-temperature silicone coating for MDF production", w: 500, h: 350,
        cap: "4106S — single-layer base with a high-temperature silicone coat.",
        txt: "Where resin-laden product must release cleanly, 4106S coats a single-layer fabric with high-temperature silicone — a version supplied specifically for MDF and board production." },
      { t: "Strand & particle belt dryers", link: "spiral-belt",
        img: "/qfy-content/uploads/sp/sp-pet.jpg", alt: "Open PET spiral fabric belt for OSB strand and particle drying", w: 1000, h: 750,
        cap: "Open spiral construction — the drying air reaches the product.",
        txt: "Multi-layer belt dryers move OSB strands and particles on open spiral fabrics — no filler yarns, up to ~1000 CFM, so hot air passes through belt and product instead of fighting it." },
      { t: "Biomass & pellet drying", link: "products/square-mesh",
        img: "/qfy-content/uploads/df/sq-blue.jpg", alt: "Blue polyester square mesh belt for wood chip and biomass drying", w: 1200, h: 900,
        cap: "Square mesh — fine, stable, heat-set.",
        txt: "Fine square mesh belts for wood chip, shavings and pellet dryers — heat-set polyester that stays flat and stable to 180 °C; compatible with / alternative to OEM mesh belts." },
      { t: "Press & cooling decks", link: "spiral-belt",
        txt: "PTFE belts for release-sensitive press-outfeed duties and spiral belts for cooling and conveying decks." },
    ],
    oemNote: "Belts dimensioned for the common plant platforms — Dieffenbacher, Siempelkamp / Büttner, Swiss Combi-type belt dryers and Chinese line builders.",
    related: ["forming-fabric", "dryer-fabric", "spiral-belt", "products/square-mesh", "spiral-belt"],
  },
  "paper-and-pulp": {
    url: `/industries/paper-and-pulp/`, name: "Paper & Pulp",
    title: "Paper Machine Clothing | Forming, Press & Dryer Fabrics | Aurora Filtech",
    desc: "Paper machine clothing for paper mills: forming fabrics (forming wire), dryer fabrics and spiral fabrics. Packaging, printing, tissue and nonwovens.",
    kicker: "Industries · Paper & Pulp",
    intro: `Paper machine clothing is our founding trade. Aurora supplies the full wet-to-dry fabric line — forming fabrics (the forming wire of the old bronze era), dryer fabrics with anti-static yarns, and spiral fabrics for dryer and press duties — to paper mills and nonwovens producers.`,
    banner: { img: "/qfy-content/uploads/live/forming-f.jpg", alt: "Paper machine production line running Aurora forming fabrics", w: 800, h: 252,
      cap: "Paper machine wet end — where the forming fabric does its work." },
    processes: [
      { t: "Forming section", tag: "FF series", link: "forming-fabric",
        img: "/qfy-content/uploads/live/forming-g1.jpg", alt: "Polyester forming fabric running in the wet end of a paper machine", w: 800, h: 400,
        cap: "Forming fabric — 1-layer to 3-layer SSB.",
        txt: "Aurora FF forming fabrics — 1-layer to 3-layer SSB in anti-hydrolysis monofilament, matched to machine speed, retention and drainage for packaging, printing & writing and tissue grades." },
      { t: "Dryer section — flat-yarn fabrics", tag: "DF series", link: "dryer-fabric",
        img: "/qfy-content/uploads/df/single-flat.jpg", alt: "Single-layer flat yarn dryer fabric for paper machine drying sections", w: 466, h: 350,
        cap: "Single-layer flat-yarn dryer fabric.",
        txt: "More than ten flat- and round-yarn constructions for paper machine dryer decks — specified by air permeability (CFM), layer count and sheet-side smoothness." },
      { t: "High-smoothness duties — double layer", link: "dryer-fabric",
        img: "/qfy-content/uploads/df/double-layer.jpg", alt: "Double-layer flat yarn dryer fabric for quality paper grades", w: 490, h: 368,
        cap: "Double-layer flat-yarn dryer fabric.",
        txt: "Two flat-yarn layers give a smoother, more stable sheet run after the press section — the construction for grades where contact marks would end up in the finished sheet." },
      { t: "Open, high-airflow decks", link: "spiral-belt",
        img: "/qfy-content/uploads/sp/sp-9010-4.jpg", alt: "Spiral fabric with PET filler yarns for open paper machine drying decks", w: 466, h: 350,
        cap: "Spiral fabric with PET filler yarns.",
        txt: "Where decks run hot and open, spiral fabrics move air without tracking — PET as standard, PPS for high-temperature positions." },
      { t: "Pulp mill filtration", link: "vacuum-fabric",
        img: "/qfy-content/uploads/live/pulp-nylon.jpg", alt: "PA nylon press mesh for pulp dewatering, the press-ap pulp fabric", w: 900, h: 675,
        cap: "PA nylon press mesh for pulp — and vacuum fabrics for washing.",
        txt: "Two cloths for the pulp mill: vacuum filter fabrics for disc, drum and belt washing/thickening duties — and our PA nylon press mesh for pulp pressing (the press-ap fabric): nylon outperforms PET on hot alkaline stock, and our proprietary formulation lasts 2× longer than competing cloths." },
    ],
    oemNote: "Fabrics to fit Fourdrinier, hybrid and gap former machines; also nonwoven spunlace, needle-punch and airlaid lines.",
    related: ["forming-fabric", "dryer-fabric", "spiral-belt", "vacuum-fabric"],
  },
  "mining": {
    url: `/industries/mining/`, name: "Mining & Minerals",
    title: "Mining Filtration Fabrics | Dewatering & Tailings | Aurora Filtech",
    desc: "Filter fabrics for mining: vacuum filter fabrics, press filter cloths and spiral press belts for iron ore, copper, lithium and non-metallic minerals.",
    kicker: "Industries · Mining & Minerals",
    intro: `Mineral processing runs on filter area. Aurora supplies vacuum filter fabrics for horizontal belt, disc and drum filters (ANDRITZ / Dorr-Oliver type platforms among them), press filter cloths for frame and membrane presses, and spiral press filter belts for belt-press dewatering — across iron ore, copper, lithium and industrial minerals.`,
    banner: { img: "/qfy-content/uploads/mine/mine-banner.jpg", alt: "Open-pit mine with haul trucks moving ore on the benches", w: 1252, h: 521,
      cap: "From the pit to the filter — Aurora cloths serve the concentrator side of mining." },
    processes: [
      { t: "Horizontal vacuum belt filters", tag: "ANDRITZ / Dorr-Oliver type", link: "vacuum-fabric",
        img: "/qfy-content/uploads/vf/m620.jpg", alt: "Type 620 double-layer vacuum filter fabric for horizontal belt filters", w: 466, h: 350,
        cap: "620 — double layer, calendered surface.",
        txt: "Aurora VF fabrics for horizontal belt filters — clear filtrate, easy cake release, endless or seamed. For precision concentrate duties, 623A adds an all-monofilament plied weft: higher strength, finer filtration." },
      { t: "Disc & drum filters", link: "vacuum-fabric",
        img: "/qfy-content/uploads/pf/pf-disc.jpg", alt: "Horizontal disc vacuum filter running fan-shaped cloth segments", w: 1280, h: 720,
        cap: "Horizontal disc vacuum filter — fan-shaped segments, re-clothed by Aurora.",
        txt: "Satin-weave vacuum fabrics sized for disc and drum filter duty across ore concentrates — a long-standing construction on these platforms." },
      { t: "Press filtration (frame / membrane)", link: "press-fabric",
        img: "/qfy-content/uploads/live/pressfabric-g1.jpg", alt: "Frame press filter running press filter cloths for concentrate dewatering", w: 800, h: 348,
        cap: "Frame press filter on concentrate duty.",
        txt: "Monofilament cloths for fast cake release on concentrate duties; monofilament-multifilament combinations where filtrate clarity leads." },
      { t: "Tailings & sludge (belt press)", link: "press-belt",
        img: "/qfy-content/uploads/live/pressbelt-f.jpg", alt: "White herringbone woven press filter belt for tailings dewatering", w: 500, h: 350,
        cap: "Woven press belt — herringbone surface.",
        txt: "Woven press belts and SP-P spiral belts with filler yarns — high squeeze resistance and controlled permeability for tailings dry-stacking feed." },
      { t: "Fines classification", link: "products/square-mesh",
        txt: "Square mesh and fine screening cloth for classification sifters (40–200 mesh)." },
    ],
    oemNote: "Cloths dimensioned to the common filter platforms — ANDRITZ / Dorr-Oliver horizontal belt filters, disc and drum filters, Delkor, Pannevis, WesTech-type belts and the main press brands.",
    related: ["vacuum-fabric", "press-fabric", "spiral-belt", "products/filter-bag"],
  },
  "power-generation-fgd": {
    url: `/industries/power-generation-fgd/`, name: "Power Generation & FGD",
    title: "FGD Filtration & Baghouse Media | Power Plants | Aurora Filtech",
    desc: "FGD gypsum dewatering fabrics, sludge dewatering belts and PPS dust filter bags for coal-fired and biomass power plants.",
    kicker: "Industries · Power Generation & FGD",
    intro: `A power plant filters at both ends of the boiler: flue gas through the baghouse, and gypsum / sludge through the vacuum and press filters. Aurora supplies both — PPS dust bags for the baghouse, and the 617 / 623 vacuum fabric pair for limestone-gypsum FGD dewatering.`,
    banner: { img: "/qfy-content/uploads/vf/strip.jpg", alt: "Vacuum belt filter operation schematic with the filter fabric running on the machine", w: 960, h: 255,
      cap: "Aurora VF vacuum filter fabrics — woven, slit and seamed to your belt filter." },
    processes: [
      { t: "FGD gypsum — 617, the economical workhorse", tag: "Low permeability", link: "vacuum-fabric",
        img: "/qfy-content/uploads/vf/m617.jpg", alt: "Type 617 vacuum filter fabric with multifilament weft for FGD gypsum dewatering", w: 466, h: 350,
        cap: "617 — multifilament weft, low permeability.",
        txt: "A multifilament weft takes air permeability into a fine band — right for limestone-gypsum FGD dewatering on horizontal vacuum belt filters, and the low-cost entry point." },
      { t: "FGD gypsum — 623, the upgrade", tag: "Mono surface · scraper-resistant", link: "vacuum-fabric",
        img: "/qfy-content/uploads/vf/m623.jpg", alt: "Type 623 vacuum filter fabric with all-monofilament surface for FGD gypsum", w: 466, h: 350,
        cap: "623 — clean monofilament surface, multifilament hidden on the back.",
        txt: "Surface 100% monofilament with the multifilament buried on the machine side: the gypsum cake releases cleanly, the surface resists the scraper, and campaigns run well above 617. Thicker than 617 — check filter clearances." },
      { t: "Fly-ash & coal-ash slurries", link: "vacuum-fabric",
        txt: "The same low-permeability constructions handle fly-ash (coal-ash) slurries that need a tight cloth." },
      { t: "Baghouse dust collection", link: "products/filter-bag",
        txt: "PPS felt filter bags (membrane options) for coal-fired flue gas; PET bags for biomass and generic duties." },
      { t: "Sludge & wastewater (belt press)", link: "press-belt",
        txt: "PB woven press belts and SP-P spiral belts for dewatering FGD and plant sludges." },
    ],
    oemNote: "Bags and fabrics sized to the common FGD and baghouse platforms.",
    related: ["vacuum-fabric", "products/filter-bag", "press-belt", "products/filter-cartridge"],
  },
  "food-and-pharma": {
    url: `/industries/food-and-pharma/`, name: "Food & Pharmaceutical",
    title: "Food & Pharma Filtration and Drying Belts | Aurora Filtech",
    desc: "Food-grade dryer fabrics, PTFE (teflon) belts for vacuum dryers, spiral belts for juice and palm oil pressing. Food-contact materials.",
    kicker: "Industries · Food & Pharmaceutical",
    intro: `Food and pharma lines need belts that release cleanly and fabrics that meet the standards. Aurora supplies food-grade square mesh drying conveyors, anti-static dryer fabrics for food belt dryers, non-stick PTFE belts for vacuum belt dryers (liquid medicine, food pastes) and noodle drying lines, plus spiral press belts for juice and palm-oil pressing.`,
    banner: { img: "/qfy-content/uploads/df/sq-fruit-w.jpg", alt: "Dried vegetables resting on a square mesh food drying conveyor belt", w: 1000, h: 500,
      cap: "Food duty — dried vegetables on a square mesh drying conveyor." },
    processes: [
      { t: "Vegetable & food drying conveyors", tag: "Food contact", link: "products/square-mesh",
        img: "/qfy-content/uploads/df/sq-white.jpg", alt: "White polyester plain weave square mesh belt for food drying and draining", w: 1200, h: 900,
        cap: "White plain-weave square mesh — food-contact material.",
        txt: "Polyester square mesh draining and drying conveyors — more than 20 heat-set apertures from 200 µm to 4 mm, flat and stable to 180 °C, in food-contact compliant materials." },
      { t: "Food belt dryers — anti-static", link: "dryer-fabric",
        img: "/qfy-content/uploads/df/as-mixed.jpg", alt: "Anti-static dryer fabric with mixed conductive yarn and copper wire for food belt dryers", w: 466, h: 350,
        cap: "Anti-static construction for food belt dryers.",
        txt: "Food-grade anti-static dryer fabrics for belt dryers — no dust cling, no product wrap-up, stable air permeability between washes." },
      { t: "Vacuum belt drying (liquid medicine, extracts)", link: "spiral-belt",
        txt: "Non-stick PTFE belts for multi-layer vacuum belt dryers — mesh belts for evaporation, solid belts for pastes — the standard duty for liquid medicine and food extracts." },
      { t: "Noodle drying belts", link: "spiral-belt",
        txt: "PTFE and polyester drying belts for noodle and strip-product drying lines — non-stick surfaces, anti-static options." },
      { t: "Juice & palm oil pressing", link: "spiral-belt",
        img: "/qfy-content/uploads/live/pressbelt-f.jpg", alt: "Woven press belt fabric for juice and palm oil squeezing lines", w: 500, h: 350,
        cap: "Press belt fabric — smooth, easy-cleaning surface.",
        txt: "SP-P spiral press belts with flat filler yarns and woven press belts — smooth surface, high juice yield, easy cleaning." },
      { t: "Sieving & sifting", link: "products/square-mesh",
        txt: "Fine polyester square mesh for flour, powder and ingredient sieving (40–200 mesh)." },
    ],
    oemNote: "Food-contact compliant materials on request; document pack available.",
    related: ["spiral-belt", "dryer-fabric", "spiral-belt", "products/square-mesh"],
  },
  "nonwovens": {
    url: `/industries/nonwovens/`, name: "Nonwovens",
    title: "Nonwoven Forming Belts & Conveyor Meshes | Aurora Filtech",
    desc: "Forming belts and conveyor meshes for nonwoven production — drylaid, airlaid, spunlaid (spunbond & meltblown) and wetlaid. Polyester, PPS and stainless steel.",
    kicker: "Industries · Nonwovens",
    intro: `Every nonwoven starts as a web laid on a forming belt, and is consolidated in a second step — hydroentanglement (spunlace), needle punch or thermal bonding. The route differs; the belt is the constant. Aurora weaves the forming belts and conveyor meshes for all four web-formation routes — drylaid, airlaid, spunlaid and wetlaid — plus the dryer fabrics downstream. Anti-static, quick-draining, fiber-retaining, in polyester, PPS or stainless steel.`,
    banner: { img: "/qfy-content/uploads/nw/nw-banner.jpg", alt: "Nonwoven production line with forming belt carrying the fiber web", w: 1200, h: 377,
      cap: "Aurora forming belts and conveyor meshes for nonwoven web formation." },
    processes: [
      { t: "Drylaid — carding &amp; cross-lapping", tag: "Web formation", link: "products/square-mesh",
        imgs: ["/qfy-content/uploads/nw/nw-diag-drylaid.jpg", "/qfy-content/uploads/nw/nw-pr-drylaid.jpg"],
        alts: ["Drylaid nonwoven process diagram: carding and cross-lapping build the batt", "Dryer screen mesh — fine square mesh belt carrying the drylaid batt"],
        cap: "Drylaid route (left) — the dryer screen mesh that carries the batt (right).",
        txt: "Staple fibers are opened, carded and cross-lapped into a batt on the forming belt. The belt under a drylaid line is a fine square mesh (dryer screen mesh): heat-set, flat and dimensionally stable, so the batt builds evenly and the belt tracks true through card and lapper, run after run." },
      { t: "Airlaid", tag: "Web formation", link: "products/square-mesh",
        imgs: ["/qfy-content/uploads/nw/nw-diag-airlaid.jpg", "/qfy-content/uploads/nw/nw-pr-airlaid.jpg"],
        alts: ["Airlaid nonwoven process diagram: fibers dispersed in air and deposited under vacuum", "Forming fabric for airlaid nonwoven fabric production"],
        cap: "Airlaid route (left) — the forming fabric under the former (right).",
        txt: "Short fibers and pulp are dispersed in air and deposited onto a forming fabric, with vacuum beneath pulling the web together in one step. Air permeability and fiber retention decide how even that web is — the two properties we tune first on an airlaid forming belt." },
      { t: "Spunlaid — spunbond &amp; meltblown", tag: "Web formation", link: "dryer-fabric",
        imgs: ["/qfy-content/uploads/nw/nw-diag-spunlaid.jpg", "/qfy-content/uploads/nw/nw-pr-spunlaid.jpg"],
        alts: ["Spunlaid nonwoven process diagram: filaments laid onto the forming screen", "Anti-hydrolysis dryer fabric used downstream of spunlaid nonwoven lines"],
        cap: "Spunlaid route (left) — anti-hydrolysis dryer fabric downstream (right).",
        txt: "Polymer is spun, drawn and laid directly onto a forming screen under the spinneret — vacuum boxes beneath pull air through so the filament web lies flat. Downstream of bonding, anti-hydrolysis dryer fabrics carry the web through the line; the screen mesh for spunlaid and this dryer fabric usually come as a set from us." },
      { t: "Wetlaid", tag: "Web formation", link: "forming-fabric",
        imgs: ["/qfy-content/uploads/nw/nw-diag-wetlaid.jpg", "/qfy-content/uploads/nw/nw-pr-wetlaid.jpg"],
        alts: ["Wetlaid nonwoven process diagram: web formed from a fiber slurry, then bonded and dried", "Wetlaid forming fabric for nonwoven fabric production"],
        cap: "Wetlaid route (left) — the wetlaid forming fabric (right).",
        txt: "Wetlaid lines form the web from a fiber slurry, exactly as a paper machine does: the forming fabric drains water while retaining fiber. Fine, uniform openings and easy cleaning make our wetlaid forming fabrics a natural extension of the paper machine clothing we have woven for 30 years." },
      { t: "Seam types", tag: "Single loop · double rim · endless", link: "spiral-belt",
        gallery: [
          { src: "/qfy-content/uploads/nw/nw-seam-single.jpg", alt: "Single loop seam of a nonwoven filter fabric belt, close-up", cap: "Single loop seam" },
          { src: "/qfy-content/uploads/nw/nw-seam-double.jpg", alt: "Double rim seam on an anti-static nonwoven dryer fabric", cap: "Double rim seam — anti-static fabrics" },
          { src: "/qfy-content/uploads/nw/nw-seam-endless.jpg", alt: "Endless joint nonwoven belt, close-up of the seamless edge", cap: "Endless joint" },
        ],
        txt: "Every belt is joined to suit the machine: single loop for quick change-outs, double rim — standard on our anti-static fabrics — or a truly endless joint where the most sensitive webs demand it." },
      { t: "Materials, temperature &amp; duty", tag: "PET · PPS · stainless steel", link: "spiral-belt",
        txt: "Nonwoven belts run from 180 °C up to 260 °C duty — polyester as standard, PPS and stainless steel where heat demands it. Special weave structures keep the belt stable under needle looms and high-pressure water jets alike, and high air flow through the belt is what makes web bonding efficient." },
    ],
    oemNote: "Fabrics to fit the common nonwoven line platforms.",
    related: ["dryer-fabric", "products/square-mesh", "spiral-belt"],
  },
};

// ---- 应用专页(2, 方孔网体系) ----
const applications = {
  "wood-mesh-belts": {
    url: `/industries/wood-based-panels/mesh-belts/`, name: "Wood Panel & Biomass Mesh Belts",
    title: "Wood Panel & Biomass Drying Mesh Belts | Aurora Filtech",
    desc: "Square mesh and spiral dryer belts for wood chip, shavings, strand and pellet drying — alternative to OEM mesh belts for panel board plants.",
    kicker: "Application · Wood Panel Mesh Belts",
    intro: `Wood panel and biomass dryers run on permeable mesh belts: chips, shavings and strands carried on decks where hot air is pulled through belt and product. Aurora SM square mesh belts and SP-D spiral dryer fabrics serve these decks — woven to the same disciplines as the OEM mesh belts they replace, at direct factory pricing.`,
    sections: [
      { t: "Drying decks (chips, shavings, pellets)", txt: "Fine square mesh belts in plain weave PET — quiet running, stable tracking, high open area for through-air drying.", link: "products/square-mesh" },
      { t: "Strand & particle dryers (OSB / PB)", txt: "Open spiral dryer fabrics without filler yarns, up to ~900 CFM, anti-static versions available.", link: "spiral-belt" },
      { t: "Forming & pre-press", txt: "Anti-static forming fabrics for forming lines and pre-press inlets.", link: "forming-fabric" },
    ],
    oemNote: "Alternative / compatible with OEM mesh belts on the common belt dryer platforms (Swiss Combi and Büttner-type low-temperature belt dryers; Chinese line builders). Send us the old belt's drawing or a photo of its data tag.",
    related: ["products/square-mesh", "spiral-belt", "dryer-fabric"],
  },
  "wood-flour-sifting": {
    url: `/industries/wood-flour-sifting/`, name: "Wood Flour & Fines Sifting",
    title: "Wood Flour Sieving Mesh for WPC | Aurora Filtech",
    desc: "Polyester square mesh (40-140 mesh count) for wood flour and WPC fines classification on vibrating, gyratory and circular sifters.",
    kicker: "Application · Wood Flour Sifting",
    intro: `Wood-plastic composite (WPC) lines classify wood flour on vibrating, rotating or oscillating screens — typically 40 to 140 mesh, with 60 and 80 mesh the common cuts. Aurora SM polyester square mesh gives stainless-steel precision at lighter weight and lower cost on these dry, low-abrasion duties, supplied as cut panels edged to your frame or as re-mesh for circular sifters.`,
    sections: [
      { t: "Mesh count selection", txt: "40–140 mesh for WPC flour; aperture and open area per count in our spec table.", link: "products/square-mesh" },
      { t: "Panels & re-mesh", txt: "Cut and edged panels for gyratory / oscillating sifters; re-mesh service for SWECO-type circular separators.", link: "products/square-mesh" },
      { t: "Fines recovery on panel lines", txt: "Sifting mesh for fines streams beside the main (roller / disc) screen lines.", link: "products/square-mesh" },
    ],
    oemNote: "Popular in North American WPC and panel plants; also supplied for general flour and powder sieving.",
    related: ["products/square-mesh", "products/filter-cartridge"],
  },
};

// ---- 博客(首批 3 篇) ----
const posts = {
  "forming-fabric-guide": {
    url: `/blog/forming-fabric-guide/`, title: "What Is a Forming Fabric (Forming Wire)? A Practical Guide",
    desc: "What a forming fabric (forming wire) is, layer constructions, mesh count and CFM explained, and how to choose — a practical guide from Aurora Filtech.",
    date: "2026-09-10", tag: "Paper Machine Clothing",
    related: ["forming-fabric", "dryer-fabric", "spiral-belt"],
    body: [
      ["h2", "What is a forming fabric?"],
      ["p", "A forming fabric is the woven monofilament belt that forms and dewaters the fiber web at the wet end of a paper machine or nonwoven forming line. Stock sprays onto the fabric; water drains through its openings while the fibers stay on top to become the sheet. It is still commonly called a forming wire — or simply the wire — because early machines ran on woven bronze wires. Polyester monofilament replaced bronze decades ago, but crews kept the name: forming fabrics, commonly called a wire."],
      ["h2", "Forming fabric vs forming wire vs paper machine clothing"],
      ["p", "Three names, three levels. Forming fabric is today's standard product name — the one used across the major suppliers' catalogues. Forming wire is the trade nickname for the same product. Paper machine clothing (PMC) is the umbrella category: forming fabrics, press fabrics and dryer fabrics together. When you order, order by function (forming), construction (layers) and specification (mesh count, CFM) — not by nickname."],
      ["h2", "How a forming fabric works"],
      ["p", "The fabric does three jobs at once: it drains water through calibrated openings, it supports and carries the fragile fiber web, and it transmits drive force over the foils, vacuum boxes and couch roll without marking the sheet. Everything about its design — yarn diameter, weave pattern, layer count — is a trade-off between drainage speed and fiber retention."],
      ["h2", "Layer constructions: 1-layer, 1.5-layer, 2-layer, 3-layer"],
      ["ul", ["1-layer — maximum drainage and caliper stability for fast machines and heavy stock.", "1.5-layer — extra CD yarns for better retention with most of the drainage kept.", "2-layer — smoother sheet side for printing and packaging grades.", "3-layer (SSB, triple layer) — separate sheet side and machine side: fine top for formation, coarse bottom for stability. The default for quality grades."]],
      ["h2", "Mesh count and air permeability (CFM)"],
      ["p", "Mesh count is the number of MD and CD yarns per centimetre — more yarns mean smaller openings and better retention. Air permeability (CFM) measures how much air the fabric passes at a standard pressure; suppliers match CFM to your stock, speed and vacuum design. A fabric that is too open loses fiber and fines; one that is too tight chokes drainage and loads the vacuum system."],
      ["h2", "How to choose a forming fabric"],
      ["ul", ["Start from the machine: former type, speed, and vacuum layout.", "Then the product: packaging, printing & writing, tissue, or nonwoven web.", "Then the failure history: blinding calls for monofilament and higher CFM; fiber loss calls for finer counts or multi-layer.", "Always specify seams and edges to the machine's design — pin, clipper or endless."]],
      ["h2", "Aurora forming fabrics"],
      ["p", "Aurora FF series covers 1-layer to 3-layer SSB constructions in anti-hydrolysis polyester monofilament, for paper machines, nonwoven forming lines and special duties like graphite flake forming. Ask our engineers for a drainage audit on your machine — specifying by duty, not by habit, is the cheapest dewatering upgrade available."],
    ],
  },
  "spiral-fabric-guide": {
    url: `/blog/spiral-fabric-guide/`, title: "Spiral Fabric Guide: Dryer Fabric vs Press Belt, and Filler Yarns Explained",
    desc: "Spiral fabric explained: spiral links, filler yarns (round vs flat), spiral dryer fabric vs spiral press filter belt, and how to choose.",
    date: "2026-09-10", tag: "Spiral Fabrics",
    related: ["spiral-belt", "spiral-belt"],
    body: [
      ["h2", "What is a spiral fabric?"],
      ["p", "A spiral fabric is an industrial belt assembled from monofilament spirals joined by hinge pins (cross yarns through the adjacent loops) — not woven on a loom, but built like a chain of springs. The structure runs true without tracking guides, drains fast, cleans easily and can be repaired link by link on the machine. That is why it is the workhorse belt of dryers and belt press filters alike."],
      ["h2", "Two families: without and with filler yarns"],
      ["p", "The same platform serves two opposite duties, tuned by filler yarns — extra monofilaments inserted into the spiral loops:"],
      ["ul", ["Without filler yarns — the spiral stays open (up to ~900 CFM). Air passes freely: ideal for dryer fabrics, through-air drying and conveying.", "With 1–5 filler yarns — density rises and air permeability drops (into the 20–150 CFM band). Fines stay on the belt: ideal for filter duties on belt press filters."]],
      ["h2", "Round or flat filler yarns?"],
      ["ul", ["Round monofilament fillers maximize open area and CFM, keeping drainage channels clear longer.", "Flat monofilament fillers give a smoother surface and better fines retention while still breathing well — the usual choice for juice and palm oil pressing."]],
      ["h2", "Naming: spiral fabric, spiral dryer fabric, spiral belt"],
      ["p", "Spiral fabric is the family name and matches the structure you see in image searches. By duty: spiral dryer fabric (drying, no fillers) and spiral press filter belt / dewatering belt (filtration, with fillers). Spiral belt alone is a common alias — but be aware it is also used for the metal and plastic spiral-tower conveyor belts of the food freezing industry, a different product entirely. When searching or specifying, add the duty word: dryer or press."],
      ["h2", "Spiral vs woven dryer fabric"],
      ["p", "Spirals drive efficiency upstream: in the wet, high-air zones their openness moves the most air. Woven fabrics run smoother and more stably at the hottest, fastest positions. The field rule — spirals early, wovens late — holds for most paper, panel and nonwoven dryers."],
      ["h2", "How to specify a spiral fabric"],
      ["ul", ["Duty first: drying/conveying (no fillers) or filtration (1–5 fillers).", "Then permeability target in CFM — we tune filler count and cross-section to hit it.", "Material: PET standard; PPS for around 240 °C long-term duty.", "Seam: spiral pin seam standard; endless on request.", "Edges: sealed, welded or reinforced to your machine."]],
      ["p", "Aurora SP series covers both families from one weaving platform — see the spiral fabric overview for the full family map."],
    ],
  },
  "ptfe-belt-joint-types": {
    url: `/blog/ptfe-belt-joint-types/`, title: "PTFE / Teflon Belt Joint Types Compared: Bullnose, Scarfed, Pin & Endless",
    desc: "PTFE belt joint types compared: bullnose, scarfed, pin (alligator) and endless — strength, smoothness and when to use each joint.",
    date: "2026-09-10", tag: "PTFE Belts",
    related: ["spiral-belt", "dryer-fabric", "spiral-belt"],
    body: [
      ["h2", "Why the joint decides your belt's life"],
      ["p", "On a teflon (PTFE) coated glass belt, the joint is almost always the first thing to fail — it is the one place where the smooth, non-stick surface is interrupted. Choosing the right joint type for your dryer or conveyor is therefore a maintenance decision, not a detail."],
      ["h2", "The four standard PTFE belt joints"],
      ["ul", ["Bullnose overlap — both ends folded into a rounded nose that overlaps. Fast to fit, easy to re-lace on the machine; slight thickness bump at the joint. The everyday choice for medium duties.", "Scarfed (bias) overlap — the overlap is planed to a taper so the joint stays close to belt thickness. Smoother running over rollers and knife edges; the standard for solid belts and product-marking-sensitive duties.", "Pin / alligator joint — metal or plastic pin hinges joining the ends. Strong, openable for cleaning, good for mesh belts; the metal pin must suit the temperature.", "Endless (seamless) — woven or welded with no joint at all. The smoothest and strongest option for vacuum belt dryers; needs the belt made to final length."]],
      ["h2", "Which joint for which duty?"],
      ["ul", ["Vacuum belt dryers, food & pharma: endless or scarfed — anything that minimises marking and product trap points.", "Tunnel dryers, general drying: bullnose or pin — quick to fit, tolerant of temperature cycling.", "Mesh belts for high-air drying: pin joints — they preserve the open area.", "Frequent clean-downs: pin or bullnose — both can be opened for cleaning."]],
      ["h2", "Specifying joints with Aurora"],
      ["p", "Tell us the dryer type, temperature, product and whether the belt passes over knife edges or vacuum plates — we will match joint type, thickness and edge treatment. Aurora TB belts are supplied with bullnose, scarfed, pin or endless joints, in mesh and solid constructions."],
    ],
  },
};

// ---- 术语表 ----
const glossary = [
  ["Air permeability (CFM)", "The volume of air (cubic feet per minute) passed by one square foot of fabric at a standard pressure drop. The core specification for dryer and filter fabrics."],
  ["Anti-hydrolysis yarn", "Polyester monofilament stabilised against hot-water attack — standard for humid forming sections and FGD duties."],
  ["Anti-static yarn", "Conductive (usually carbon-cored) filament woven into the fabric to drain static charges on high-speed dryers."],
  ["Belt press filter", "A continuous filter that squeezes sludge between two moving belts through gravity, wedge and pressing zones."],
  ["Bullnose joint", "A PTFE belt joint where folded, rounded belt ends overlap — quick to fit and re-lace."],
  ["CFM", "See Air permeability. Typical spiral dryer fabrics reach ~900 CFM; filled press belts run 20–150 CFM."],
  ["Clipper seam", "A metal clip (wire hook) seam joining belt ends — strong and repairable."],
  ["Disc filter", "A rotary vacuum filter with segmented discs covered by filter fabric sectors."],
  ["Dryer fabric", "The fabric carrying paper/board/food through heated dryer sections; also called dryer belt."],
  ["FGD", "Flue gas desulfurization — its gypsum by-product is dewatered on vacuum belt filters."],
  ["Filler yarns", "Extra monofilaments inserted into spiral belt loops to raise density and lower permeability (1–5 yarns; round or flat section)."],
  ["Filter press cloth", "Fabric (monofilament, multifilament, staple or combinations) cut and sewn for chamber / membrane filter plates."],
  ["Forming fabric", "The wet-end belt that forms and dewaters the fiber web; historically called forming wire (from the bronze-wire era)."],
  ["Forming wire", "Trade name for a forming fabric — still standard among machine crews and in B2B listings."],
  ["Fourdrinier", "The classic flat-wire paper machine; the forming section is still often called the wire section."],
  ["Horizontal vacuum belt filter (HVBF)", "A continuously indexing or endless-belt vacuum filter for dewatering and washing duties."],
  ["Mesh count", "The number of openings per centimetre (or per inch) of a woven mesh — higher count, finer opening."],
  ["Monofilament", "A single smooth yarn — best cake release and blinding resistance in filter cloths."],
  ["Multifilament", "A yarn twisted from many filaments — finer retention, clearer filtrate, harder cake release."],
  ["Open area", "The percentage of fabric surface that is opening; high open area = high flow."],
  ["Paper machine clothing (PMC)", "The umbrella term for forming, press and dryer fabrics on a paper machine."],
  ["Pin seam", "A joint where a pin (or clipper wire) runs through loops formed in the belt ends."],
  ["PPS", "Polyphenylene sulphide — a monofilament/felt polymer for hot, chemical duty (~240 °C long-term in spiral fabrics)."],
  ["PTFE", "Polytetrafluoroethylene — non-stick, food-grade, 260 °C; used as belt coating and membrane material."],
  ["Scarfed joint", "A PTFE belt joint planed to a taper so the overlap stays near belt thickness — smooth over rollers."],
  ["Screen mesh / sifter mesh", "Woven mesh fitted as the working surface of a vibrating, gyratory or circular sifter."],
  ["Spiral dryer fabric", "Spiral-link belt without filler yarns — open structure (up to ~900 CFM) for drying and conveying."],
  ["Spiral press filter belt", "Spiral-link belt with 1–5 filler yarns — dense, low-permeability filter belt for belt press filters."],
  ["SSB (triple layer)", "Sheet-side / machine-side triple-layer forming fabric construction for quality paper grades."],
  ["Square weave mesh", "Plain-weave (1/1) mesh with precise square openings, e.g. 40–200 mesh count polyester."],
  ["Tube sheet", "The perforated plate of a baghouse that filter bags hang from — bags are sized to it."],
  ["Vacuum filter fabric", "Fabric for vacuum belt, disc and drum filters, in PET / PP / PVDF."],
];

module.exports = { industries, applications, posts, glossary };
